language: perl6

perl6:
  - latest

os:
  - linux

install:
  - apt update
  - apt install -y asciidoc
  - rakudobrew build zef
  - zef install --deps-only --force-resolve .

script: AUTHOR_TESTING=1 prove -v -e "perl6 -Ilib" t/
